theme: jekyll-theme-minimal
title: <p align="center"> Prahith N </p>
logo: /assets/img/logo2.jpeg

description:
  </p>
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prahith-n-2a0ab2184/">LinkedIn</a> |
  <a href="https://github.com/Prahith1">GitHub</a>
  

theme: jekyll-theme-minimal
